# Configuration for CI build at https://travis-ci.org/JetBrains/idea-gitignore

language: java

jdk:
  - oraclejdk8

dist: trusty

env:
  - IDEA_VERSION=192.5728.98

# Workaround for https://github.com/travis-ci/travis-ci/issues/5227
# Buffer overflow in Java_java_net_Inet4AddressImpl_getLocalHostName
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew assemble

after_success:
  - ./gradlew jacocoTestReport coveralls
